version: '3.7'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
volumes:
  mongodb_data:
    name: mongodb-data
# docker run -it --entrypoint 'mongod --bind_ip_all' --hostname MONGODB --name=MONGODB --net=bridge --expose=27017 mongo